config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'password_resets/new'
    get 'password_resets/edit'
    get 'sessions/new'
    root 'static_pages#home'
    get '/home', to: 'static_pages#home'
    get '/users', to: 'users#index'
    get '/help', to: 'static_pages#help'
    get '/about', to: 'static_pages#about'
    get '/contact', to: 'static_pages#contact'
    get '/signup', to: 'users#new'
    get '/search', to: 'users#search'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

    resources :users

    resources :users do
      member do
        get :following, :followers
      end
    end
    
    resources :microposts
    resources :comments
    resources :likes 

    
    resources :relationships, only: [:create, :destroy]

    # your routes here...
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_comment_form.html.erb
  <%= form_with(model: @comment,  local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, class: "form-control", required: true%>
    </div>
    <%= hidden_field_tag :micropost_id, micropost_id %>
    <% if !:content.blank? %>
      <%= f.submit "Comment", class: "btn btn-primary" %>
    <% end %>
    <br />
  <% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
        <div class="alert alert-danger">
            The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <% object.errors.full_messages.each do |msg| %>
            <ul>
                <li> <%= msg %> </li>
            </ul>
        <% end %>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if  @feed_items.any? %>
    <ol class="microposts">
        <%= render @feed_items %>
    </ol>
    <%= will_paginate @feed_items, params: { controller: :static_pages, action: :home } %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t('global.home.postForm.CreateMicroPost'), class:'form-control', required:true %>
  </div>
  <%= f.submit t('global.home.postForm.PostBtnTitle'), class: "btn btn-primary" %>
  <span style="margin-top:10px;" class="image">
   
  </span>

  <div class="mb-3">
  <label for="formFileSm" class="form-label"><%= t('global.AddImage') %></label>
   <%= f.file_field :image,  class: "form-control form-control-sm" %>
</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span><%= link_to t('global.home.viewMyProfile'), current_user %></span>
<span>
  <%= pluralize(current_user.microposts.count, t("global.home.micropost") )%>
</span>