config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'password_resets/new'
    get 'password_resets/edit'
    get 'sessions/new'
    root 'static_pages#home'
    get '/home', to: 'static_pages#home'
    get '/users', to: 'users#index'
    get '/help', to: 'static_pages#help'
    get '/about', to: 'static_pages#about'
    get '/contact', to: 'static_pages#contact'
    get '/signup', to: 'users#new'
    get '/search', to: 'users#search'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

    resources :users

    resources :users do
      member do
        get :following, :followers
      end
    end
    
    resources :microposts
    resources :comments
    resources :likes 

    
    resources :relationships, only: [:create, :destroy]

    # your routes here...
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="https://www.railstutorial.org/">Ruby on Rails
            Tutorial</a>
        by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
        <ul>

            <li><%= link_to t('global.About'), about_path %></li>
            <li><%= link_to t('global.Contact'), contact_path %></li>
            <li><a href="https://news.railstutorial.org/"><%= t('global.News') %></a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("global.Sample_App"), '#', id: "logo" %>
    <nav class="header_nav">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1"
            aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right lg-menu-nav">
        <li><%= link_to t('global.Home'), root_path %></li>
        <li><%= link_to t('global.Help'), help_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= t('global.Languages') %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to t('global.Amharic'),  root_path(locale: :amh) %></li>
            <li><%= link_to t('global.English'),  root_path(locale: :en) %></li>
          </ul>
        </li>
        <% if logged_in? %>
          <li><%= link_to t('global.Users'), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('global.Account') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('global.Profile'), current_user %></li>
              <li><%= link_to t('global.Setting'), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t('global.Logout'), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('global.Login'), login_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right collapse navbarcollapse" id="bs-example-navbar-collapse-1">
        <li><%= link_to t('global.Home'), root_path %></li>
        <li><%= link_to t('global.Help'), help_path %></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('global.Languages') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('global.Amharic'),  root_path(locale: :amh) %></li>
              <li><%= link_to t('global.English'),  root_path(locale: :en) %></li>
            </ul>
        </li>
        <% if logged_in? %>
          <li><%= link_to t('global.Users'), users_path %></li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('global.Account') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('global.Profile'), current_user %></li>
              <li><%= link_to t('global.Setting'), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t('global.Logout'), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('global.Login'), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script
src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.j
s">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>
        <%= full_title(yield(:title)) %>
    </title>
    <meta name="viewport" content="width=device-width, initialscale=1"> 
    <%= csrf_meta_tags %>  
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<%= render 'layouts/shim' %>

<body>
    <%= render 'layouts/header' %>
   
    <div class="container">
        <i class="bi bi-pencil-fill"></i>
        <% flash.each do |msg_type, msg| %>
            <div class="alert alert-<%= msg_type %>">
                <%= msg %>
            </div>
        <% end %>
        <%= yield %>
    </div>

     <%= render 'layouts/footer' %>
     <%# <%= debug(params) %>

</body>

</html>